import Foundation
import CoreLocation

class MapViewModel: ObservableObject {
    @Published var buildings: [CampusBuilding] = []

    init() {
        loadBuildings()
    }

    func loadBuildings() {
            buildings = [
                CampusBuilding(name: "Office of Sustainability",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5112, longitude: -88.9877)),
                CampusBuilding(name: "Kingsley Building Suite B",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5115, longitude: -88.9910)),
                CampusBuilding(name: "Administration Building #1",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5119, longitude: -88.9929)),
                CampusBuilding(name: "Alumni Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5122, longitude: -88.9953)),
                CampusBuilding(name: "Ropp Agriculture Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5097, longitude: -88.9965)),
                CampusBuilding(name: "Art Studio Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5120, longitude: -88.9937)),
                CampusBuilding(name: "Bowling & Billiards Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5110, longitude: -88.9880)),
                CampusBuilding(name: "Bone Student Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5141, longitude: -88.9893)),
                CampusBuilding(name: "Braden Auditorium",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5142, longitude: -88.9895)),
                CampusBuilding(name: "Centennial East",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5124, longitude: -88.9874)),
                CampusBuilding(name: "Center for Civic Engagement",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5117, longitude: -88.9925)),
                CampusBuilding(name: "Cook Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5130, longitude: -88.9901)),
                CampusBuilding(name: "Center for Performing Arts",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5127, longitude: -88.9917)),
                CampusBuilding(name: "College Place Uptown",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5139, longitude: -88.9945)),
                CampusBuilding(name: "Campus Recreation Operations",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5110, longitude: -88.9876)),
                CampusBuilding(name: "Center for the Visual Arts",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5120, longitude: -88.9937)),
                CampusBuilding(name: "Centennial West",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5118, longitude: -88.9876)),
                CampusBuilding(name: "Duffy Bass Field",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5095, longitude: -88.9952)),
                CampusBuilding(name: "DeGarmo Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5135, longitude: -88.9884)),
                CampusBuilding(name: "WGLT Radio",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5116, longitude: -88.9882)),
                CampusBuilding(name: "Edwards Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5131, longitude: -88.9904)),
                CampusBuilding(name: "Ewing Manor",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5122, longitude: -88.9953)),
                CampusBuilding(name: "University Farm Areas",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5050, longitude: -88.9950)),
                CampusBuilding(name: "Fell Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5127, longitude: -88.9935)),
                CampusBuilding(name: "Fairchild Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5137, longitude: -88.9919)),
                CampusBuilding(name: "Felmley Hall of Science",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5133, longitude: -88.9887)),
                CampusBuilding(name: "John Green",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5105, longitude: -88.9910)),
                CampusBuilding(name: "Campus Services Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5119, longitude: -88.9929)),
                CampusBuilding(name: "Hancock Stadium",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5104, longitude: -88.9875)),
                CampusBuilding(name: "Risk Management",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5114, longitude: -88.9935)),
                CampusBuilding(name: "Hovey Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5140, longitude: -88.9921)),
                CampusBuilding(name: "Heating Plant",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5121, longitude: -88.9918)),
                CampusBuilding(name: "Honors Program Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5116, longitude: -88.9896)),
                CampusBuilding(name: "Horton Field House",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5103, longitude: -88.9873)),
                CampusBuilding(name: "ROTC Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5129, longitude: -88.9920)),
                CampusBuilding(name: "Julian Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5138, longitude: -88.9880)),
                CampusBuilding(name: "Kaufman Football Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5102, longitude: -88.9871)),
                CampusBuilding(name: "Linkins Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5144, longitude: -88.9902)),
                CampusBuilding(name: "Multicultural Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5112, longitude: -88.9903)),
                CampusBuilding(name: "MCN Simulation Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5136, longitude: -88.9912)),
                CampusBuilding(name: "Milner Library",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5124, longitude: -88.9884)),
                CampusBuilding(name: "Metcalf Lab School",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5145, longitude: -88.9916)),
                CampusBuilding(name: "Moulton Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5133, longitude: -88.9908)),
                CampusBuilding(name: "Nelson Smith Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5129, longitude: -88.9937)),
                CampusBuilding(name: "Housing & ORL",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5140, longitude: -88.9911)),
                CampusBuilding(name: "Old Union",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5118, longitude: -88.9907)),
                CampusBuilding(name: "Professional Development Building Annex",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5115, longitude: -88.9923)),
                CampusBuilding(name: "Football Practice Field",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5108, longitude: -88.9913)),
                CampusBuilding(name: "Parking Services Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5102, longitude: -88.9886)),
                CampusBuilding(name: "Redbird Adventure Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5101, longitude: -88.9879)),
                CampusBuilding(name: "Rachel Cooper",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5132, longitude: -88.9889)),
                CampusBuilding(name: "Student Accounts Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5119, longitude: -88.9917)),
                CampusBuilding(name: "Schroeder Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5123, longitude: -88.9931)),
                CampusBuilding(name: "Student Fitness Center/McCormick Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5100, longitude: -88.9870)),
                CampusBuilding(name: "State Farm Hall of Business",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5120, longitude: -88.9902)),
                CampusBuilding(name: "Science Lab Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5137, longitude: -88.9890)),
                CampusBuilding(name: "Student Services Building",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5125, longitude: -88.9925)),
                CampusBuilding(name: "Stevenson Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5130, longitude: -88.9910)),
                CampusBuilding(name: "Turner Child Care Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5113, longitude: -88.9893)),
                CampusBuilding(name: "Turner Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5115, longitude: -88.9896)),
                CampusBuilding(name: "University High School",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5141, longitude: -88.9901)),
                CampusBuilding(name: "University Residence",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5123, longitude: -88.9914)),
                CampusBuilding(name: "Uptown Station Gallery",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5131, longitude: -88.9920)),
                CampusBuilding(name: "Vitro Center",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5129, longitude: -88.9907)),
                CampusBuilding(name: "Watterson Dining Commons",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5126, longitude: -88.9908)),
                CampusBuilding(name: "Williams Hall",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5122, longitude: -88.9921)),
                CampusBuilding(name: "Warehouse Road Complex 1",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5105, longitude: -88.9891)),
                CampusBuilding(name: "Warehouse Road Complex 2",
                               coordinate: CLLocationCoordinate2D(latitude: 40.5106, longitude: -88.9892))
            ]
    }
}
